version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq_container'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  order:
    image: ghcr.io/userjalil/order-app:latest
    container_name: order
    ports:
        - 3000:3000
    depends_on:
        - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
        PORT: 3000
        AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
        - rabbitmq_network
  shipping:
    image: ghcr.io/userjalil/shipping-app:latest
    container_name: shipping
    ports:
        - 3001:3001
    depends_on:
        - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
        PORT: 3001
        AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
        - rabbitmq_network      
networks:
  rabbitmq_network:
    driver: bridge