version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout

      - run:
          name: Install cURL
          command: sudo apt-get install -y curl

      - run:
          name: Install Hadolint
          command: |
            curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64" && \
            chmod +x /usr/local/bin/hadolint

      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Build and Push Image
          command: |
            export nama_image="ghcr.io/userjalil/karsajobs:latest"
            export user_git="userjalil"            
            echo "$GIT_PASS" | docker login ghcr.io -u "$user_git" --password-stdin
            docker build -t $nama_image .
            docker push $nama_image