version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/golang:1.15
    environment:
      DOCKER_HOST: tcp://docker:2375

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout

      - run:
          name: Install cURL
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      - run:
          name: Install Hadolint
          command: |
            curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64" && \
            chmod +x /usr/local/bin/hadolint

      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

      - run:
          name: Build and Push Image
          command: | 
            echo "$DOCKER_PASS" | docker login -u userjalil --password-stdin
            docker build -t userjalil/karsajobs:latest .
            docker push userjalil/karsajobs:latest
