version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.14

    steps:
      - checkout

      - run:
          name: Install hadolint
          command: apk add --no-cache curl && \
                   curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64" && \
                   chmod +x /usr/local/bin/hadolint

      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

      - run:
          name: Install Go
          command: apk add --no-cache go

      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)