version: 2.1
jobs:
  build:
    docker:
      - image: circleci/alpine:3.14

    steps:
      - checkout

      - run:
          name: Lint Dockerfile
          command: |
            apk add --no-cache curl
            curl -sL -o /tmp/hadolint "https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64"
            chmod +x /tmp/hadolint
            /tmp/hadolint Dockerfile

      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

      - run:
          name: Build and Push Image
          command: |
            export nama_image="ghcr.io/userjalil/karsajobs:latest"
            export user_git="userjalil"
            export pass_git="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"
            
            echo "$pass_git" | docker login ghcr.io -u "$user_git" --password-stdin
            docker build -t $nama_image .
            docker push $nama_image
