version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.15-alpine

    steps:
      - checkout

      - run:
          name: Install cURL
          command: apk add --no-cache curl

      - run:
          name: Install Hadolint
          command: |
            curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64" && \
            chmod +x /usr/local/bin/hadolint

      # - run:
      #     name: Run Unit Tests
      #     command: go test -v -short --count=1 $(go list ./...)

  push:
    docker:
      - image: alpine:3.14

    steps:
      - checkout

      - run:
          name: Install Docker CLI
          command: |
            apk add --no-cache docker
            apk add --no-cache openrc
          #  rc-service docker start

      - run:
          name: Build dan Push Image
          command: |
            echo "$GIT_PASS" | docker login ghcr.io -u userjalil --password-stdin 
            RUN docker build -t ghcr.io/userjalil/karsajobs:latest . 
            RUN docker push ghcr.io/userjalil/karsajobs:latest


workflows:
  build_push_image:
    jobs:
      - build
      - push:
          requires:
            - build