apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  labels:
    app: karsajobs-ui
spec:
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/userjalil/karsajobs-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: VUE_APP_BACKEND
          value: "http://127.0.0.1:8080/"
