# gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecommerce-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# order-service VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-service-vs
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        exact: /order
    route:
    - destination:
        host: order-service
        port:
          number: 3000
      weight: 100
# ---  
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: shipping-service-vs
# spec:
#   hosts:
#   - shipping-service.default.svc.cluster.local 
#   http:
#   - route:
#     - destination:
#         host: rabbitmq-service.default.svc.cluster.local  # Ganti dengan nama host yang sesuai untuk RabbitMQ
#         port:
#           number: 5672  # Ganti dengan port yang sesuai untuk RabbitMQ


# # rabbitmq-service VirtualService
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: rabbitmq-service-vs
# spec:
#   hosts:
#   - "rabbitmq-service.default.svc.cluster.local"
#   http:
#   - route:
#     - destination:
#         host: rabbitmq-service.default.svc.cluster.local
#         port:
#           number: 5672
#       weight: 100
#     - destination:
#         host: rabbitmq-service.default.svc.cluster.local
#         port:
#           number: 15672
#       weight: 100
