apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=   # base64 dari "admin"
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==   # base64 dari "supersecretpassword"
